src/lib/index.ts, src/lib/utils/utils.ts, test/lib/index-module.test.ts
Allow for debug mode to be used in module mode
=> feat: Add debug option for module

src/lib/index.ts, test/fixtures/apiResponses/test-gomod.json, test/fixtures/apiResponsesForProjects/list-all-projects-org-playground.json, test/fixtures/snykTestsOutputs/test-gomod.json, test/lib/index-inline.test.ts
Handles cases when project name contains the targetfile appended after ':'. Typical for SCM projects, ecosystem specific for CLI.
=> fix: Handle targetfile proj name for json output proj matching

src/lib/snyk/issues.ts, src/lib/utils/issuesUtils.ts, test/fixtures/apiResponses/java-goof.json, test/fixtures/snykTestsOutputs/test-goof-without-more-vuln-following-upgrade.json, test/fixtures/snykTestsOutputs/test-java-goof-without-more-vuln-following-upgrade.json, test/lib/index-inline.test.ts
Fixes https://github.com/snyk-tech-services/snyk-delta/issues/51
Adding check to determine if new issue to exclude the cases where a vulnerable path existed before but changed slightly folowing an upgrade of one or more dependencies in it. 
Determining if a vulnerable path is not new if it matches any of the following conditions:
- vuln.id is identical between monitored snapshot and test snapshot
AND
(
- vuln paths are identical between monitored snapshot and test snapshot
OR
- every dependency of a path remain in the same order irrespective of their versions that may change
)
If an upgrade is performed but a vuln remains on that path still, the versions will change but the path should remain similar, simply with higher versions. If the top level dependency bumps the child dependencies, …
=> fix: check if vulnerable path is new and pass if not

README.md, src/lib/index.ts, src/lib/snyk/issues.ts, src/lib/snyk/snyk.ts, test/fixtures/snykTestsOutputs/test-unmonitored-goof.json, test/lib/index-inline.test.ts, test/lib/snyk/snyk.test.ts
Makes snyk-delta runs return the snyk test output if no monitored projects can be found, instead of throwing an error.
It seems to be the desired behavior of most users.
=> feat: add result passthru behavior for unmonitored projects

.circleci/config.yml
uses legacy-peer-deps to resolve install issue of semantic release.
=> fix: resolve semanticrelease peer deps issue

src/lib/snyk/issues.ts
Removes the first boolean value from the upgradePaths array in the cli output for inline mode.
=> fix: remove first expected bool val from upgradepaths array

src/lib/index.ts, test/lib/index-inline.test.ts, test/lib/index-module.test.ts
Fix bug where process.exit code was missing for module mode.
Also skipping display in jest testing module mode.
=> fix: adding missing return code in module mode

src/lib/snyk/dependencies.ts, test/fixtures/apiResponses/poetry-depgraph.json, test/fixtures/apiResponses/test-poetry.json, test/fixtures/apiResponsesForProjects/list-all-projects-org-platform.json, test/fixtures/dependencies/poetry.json, test/fixtures/snykTestsOutputs/poetry.json, test/lib/index-inline-with-proj-coord-dep-changes.test.ts
Looks up the nodeId in the graph nodes list to then extract the pkgId accordingly since NodeId != PkgId.
Does not change the behavior of the direct/indirect deps comparison, but collect the pkgId more reliably by getting the PkgId instead of assuming NodeId == PkgId, which doesn't hold true in some cases in graph generated by [this lib](https://github.com/snyk/dep-graph).
=> fix: lookup pkdId using nodeId as they are different

src/lib/snyk/issues.ts, src/lib/utils/issuesUtils.ts
Performs an initial check comparing vuln paths to compare path length and avoiding out of bound index in either path during comparison of each item of those paths.
=> fix: add check for paths lengths comparison first

src/lib/index.ts, src/lib/types.ts, test/lib/index-module-no-baseline.test.ts, test/lib/index-module.test.ts
Adds returning noBaseline indicator.
=> fix: add nobaseline indicator in module response

src/lib/index.ts, test/lib/index-module-no-baseline.test.ts
Updates the return code more precisely depending on the passIfNoBaseline flag and actual baseline being found or not.
=> fix: return right exit code in various conditions

package.json
Pins the snyk-api-ts-client to be 1.7.2. Since snyk-delta doesn't have a lock file (since it can be used as library), it downloads the latest version of the snyk-api-ts-client.
snyk-api-ts-client version 1.7.3 was released today. It generates the client programmatically from the snyk api docs. These docs just removed the /issues endpoint for project issues as it has been deprecated. While the endpoint is still functional for the current users for another couple of weeks (by which point snyk-delta will use a different endpoint to maintain its service), the new version of the client is missing what snyk delta expects, causing this issue.
Will unpin this with the next snyk-delta version which will remove the dependency on this deprecated endpoint.
=> fix: pin api client to still have issues endpoint

src/lib/index.ts, src/lib/snyk/snyk.ts, test/lib/snyk/snyk.test.ts
This change makes the getProjectUUID more discriminating when looking for project, using the package manager type for selection so project with the same name but different package manager types are distinguished.
=> fix: make uuid finding tighter with pkgMgr data

README.md
Add missing `type` param explanation
=> docs: document type parameter

src/lib/error.ts, src/lib/index.ts, test/fixtures/snykTestsOutputs/poetry.json, test/lib/index-inline-no-baseline.test.ts, test/lib/index-inline-with-proj-coord-dep-changes.test.ts, test/lib/index-inline-with-project-coordinates.test.ts, test/lib/index-inline.test.ts, test/lib/index-module-no-baseline.test.ts, test/lib/index-module.test.ts, test/lib/snyk/issues.test.ts, test/lib/utils/utils.test.ts
- baseline org is `undefined` by default
- check the baseline org is set one way or another ot throw
- check we have `.vulnerabilities` to work with from `snyk test --json` output
Throw if `snyk monitor` is the input by accident, before we failed with a runtime error as we fail to `.filter`
=> Fix: use undefined for not set baseline Org

src/lib/index.ts, src/lib/snyk/snyk_utils.ts, test/lib/index-inline.test.ts
Fixes the issue type filter that was ignored in the exit code computation.
Also fixing a exit code mock issue in test.
=> fix: apply type filter before computing exit code

src/lib/index.ts, test/lib/index-inline.test.ts
=> fix: typo in filter type in exit code

package.json, src/lib/index.ts, src/lib/snyk/snyk.ts, test/fixtures/apiResponses/customerorgSlugToUUID.json, test/fixtures/apiResponses/emptyorgSlugToUUID.json, test/lib/index-inline.test.ts, test/lib/snyk/snyk.test.ts, tsconfig.json
Swaps out organization slugs for UUID for better compatibility with v3 API and support in other tools depending on snyk-delta.
In api v1, org slugs and org ID could pretty much be used interchangeably. The CLI json output includes the org slug. Since REST api are more opinionated about the org identifier being a UUID, adding a org slug to org UUID resolution step.
It is needed to support snyk-delta version getting off projects v1 API in snyk-prevent-gh-commit-status.
=> feat: add org slug to orgUUID resolution for better v3 compatibility

.circleci/config.yml
Uses a particular version before the execa dep version upgrade in semantic release
=> fix: use specific semantic release version

.circleci/config.yml
Pin semantic release correct version for node 18 support.
Semantic release versions 23 and above drop node 18 support.
=> fix: use specific semantic release version for node18

.snyk, src/lib/snyk/snyk.ts, test/lib/index-inline.test.ts, test/lib/snyk/snyk.test.ts
Bumps api version for /orgs off deprecated beta version to ga one.
=> fix: bump orgs api endpt off deprecated version

src/lib/index.ts
Adds default api value if nothing else is set.
The intent of setting the SNYK_API env var early is to also configure the right api endpoint for the underlying snyk-request-manager library in a way that is compatible for all regions across v1 and REST endpoints.
=> fix: add default api value
