- README.md
- src/lib/index.ts
- src/lib/utils/utils.ts
- test/lib/index-module.test.ts
> release debug mode change

- README.md
Updates prerequisites in README.
> chore: Add prerequisites section to README

- README.md
- src/lib/index.ts
- test/fixtures/apiResponses/test-gomod.json
- test/fixtures/apiResponsesForProjects/list-all-projects-org-playground.json
- test/fixtures/snykTestsOutputs/test-gomod.json
- test/lib/index-inline.test.ts
> fix: release to prod

- package.json
This is necessary because it's blocking my team from moving to Node 14. 
> Support both LTS Node.js 12.x and 14.x

- package.json
Releasing changes to remove vuln.
> release fix

- package.json
sets the right engine versions and syntax
> fix: use proper node engine versions

- .circleci/config.yml
- package.json
> release changes

- src/lib/index.ts
- src/lib/snyk/issues.ts
- src/lib/types.ts
- src/lib/utils/utils.ts
- test/lib/index-inline.test.ts
- test/lib/index-module-no-baseline.test.ts
- test/lib/index-module.test.ts
- test/lib/index-standalone.test.ts
- test/lib/snyk/issues.test.ts
Add the passIfNoBaseline to the result for snyk-prevent-commit-status. 
> fix: add passIfNoBaseline to snyk-delta result

- README.md
- [] Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
> doc: option to the readme

- src/lib/index.ts
- test/lib/index-module-no-baseline.test.ts
update exit code if passing for no baseline cases
> fix: change return status code if passIfNoBaseline

- src/lib/utils/issuesUtils.ts
> fix: removing some debug lines

- README.md
- snyk_delta_all_projects.sh
- [] Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
Tested manually
> fix: Adding the workaround script for all-projects

- .snyk
- package.json
> fix: update package.json after snyk test

- .snyk
- package.json
Release fix by pinning snyk-api-ts-client
> release temporary pinning to fix breakage

- src/lib/utils/issuesUtils.ts
- test/fixtures/apiResponses/test-goof-aggregated-one-vuln-pagination.json
- test/lib/snyk/__snapshots__/issues.test.ts.snap
- test/lib/snyk/issues.test.ts
Fix test 14997, missing path
Pagination test is skip for now. It passes on its own but fail run with the suite
> fix: fix bug 14497

- src/lib/utils/issuesUtils.ts
- test/fixtures/apiResponses/test-goof-aggregated-two-vuln-one-license.json
- test/lib/snyk/__snapshots__/issues.test.ts.snap
- test/lib/snyk/__snapshots__/snyk.test.ts.snap
isIgnored and isPatched should be set at isIgnored and isPatched from aggregated issues endpoint.
Changed one of the fixtures to check this.
> fix: aggregated issues converter

- .circleci/config.yml
- [x ] Commit history is tidy [ℹ︎](https://github.com/snyk/general/wiki/Git)
change orb version for nightly tests
> fix: change orb version

- package.json
Upgrades snyk-api-ts-client to fix issues with vulns not being part of graph.
- [Related snyk-api-ts-client PR](https://github.com/snyk-tech-services/snyk-api-ts-client/pull/49)
> fix: bump api client version

- README.md
Mark repo as no longer actively maintained
> chore: mark as not actively maintained

- src/lib/index.ts
Formatting only, no changes otherwise
> chore: format with prettier

- src/lib/snyk/snyk_utils.ts
No changes apart from formatting and converting a const to func
> refactor: format file & convert to function

- src/lib/index.ts
- type the arguments
- use `??` instead of `||` when checking if set
- remove unnecessary repetition
- convert `isJestTesting` function to a constant evaluated once only `IS_JEST_TESTING`
> refactor: use ?? instead of ||

- src/lib/index.ts
- src/lib/snyk/snyk_utils.ts
Move away from using empty string as a value not set, use undefined instead to avoid issues checking if a value is present.
> fix: snykTestOutput defaults to undefined + types

- README.md
- src/lib/utils/utils.ts
- format the help text
- format the file with prettier
**Before**:
**After:**
> feat: format help text for readability

- src/lib/index.ts
Ensure baseline project id defaults to `undefined` not `''`
> fix: baseline project ID default to undefined + refactor

- package.json
Use latest version of the client that skips retries for Snyk API 404s
> feat: skip retries on 404s

- .circleci/config.yml
Run all tests on Node.js 12 to ensure support for 12+
> chore: test on node 12 for support

- .circleci/config.yml
> chore: bump node 12 image version

- .circleci/config.yml
> fix: node 12

- README.md
Update docs to confirm IAC is not supported
> docs: state that IAC is not supported

- README.md
> docs: mark as inactively maintained

- src/lib/index.ts
- src/lib/snyk/snyk_utils.ts
- test/lib/index-inline.test.ts
> Release change following typo fix

- snyk_delta_all_projects.sh
This PR fixes a typo in the echo output.
> Fix typos in bash script

- package.json
Removes the version in package.json for semantic release dev deps to avoid conflict during install.
> fix: rm semantic release from devdeps to avoid version conflict

- README.md
- docs/NOTES.md
Just adding some technical notes.
> docs: add technical notes

- .circleci/config.yml
> fix: bump node version in ci

- .circleci/config.yml
> fix: semantic release call

- .circleci/config.yml
> pins semantic release version

- .circleci/config.yml
- package.json
Fixes binary packaging.
- [Issue 190](#190)
> release binary packaging fix

- snyk_delta_all_projects.sh
Triggers release following contribution.
> fix: release and typo

- src/lib/error.ts
Reviewed the error messages for clarity and context
> Error message revision snyk-delta

- src/lib/error.ts
- test/system/standalone.test.ts
> fix: error message

- .circleci/config.yml
> fix: bump node version

- .circleci/config.yml
- src/lib/index.ts
Sets https://api.snyk.io default api value if nothing sets it. All other regions should see no change.
> release change
